### PR TITLE
Changes for Dev-68231

### PR DESCRIPTION
**Pull request by gagansingh355**

### CODE REVIEW

**Comment by ahsan13jan** [comment]
@gagansingh355 Would be great, If you could a unit test.

**Review by ahsan13jan — CHANGES_REQUESTED** [review]
Unit test would be nice to test this thing.

**Comment by gagansingh355** [comment]
> Unit test would be nice to test this thing.

Done

**Review by ahsan13jan — APPROVED** [review]
LGTM

**Pull request merged**
